version: '3.8'

services:

  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: RaveLink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  postgres_data:
